# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target “cc” do
use_frameworks!
pod 'SDWebImage', '~>3.7'
pod 'AFNetworking', '~> 2.0'
pod 'BaiduMapKit'
pod 'AMap2DMap'
pod 'AMapSearch'
pod 'RealmSwift'
#pod 'Masonry'
#pod 'Aspects'
#pod 'pop', '~> 1.0'
#
end
